### ISSUE TITLE
if "Algeb-race" is clicked, cars should switch directions as an easter egg

### ISSUE THREAD

**Issue by kathrynkodama** [jandird/AlgebRace#6]

**Comment by kathrynkodama** [comment]
Needs to be done ASAP

**Comment by kathrynkodama** [comment]
Any updates on this?

**Comment by kathrynkodama** [comment]
HIGH PRIORITY!!!

**Comment by Patrick-Tsang** [comment]
This super super secret feature may or may not have been added. 

(we'll never know, because it's SUPER SUPER secret)
